default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: postgres
  role: adam

development:
  <<: *default
  database: core_redux_dev

test:
  <<: *default
  database: core_redux_test

production:
  <<: *default
  database: core_redux_production
