default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: postgres
  role: adam

development:
  <<: *default
  database: ticketee_dev

test:
  <<: *default
  database: ticketee_test

production:
  <<: *default
  database: ticketee_production
